version: "3.4"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unsecure

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"

  php:
    container_name: unsecure-php
    build: .docker/local/php
    depends_on:
      - db
    volumes:
      - .:/home/unsecure:rw

  nginx:
    container_name: unsecure-nginx
    image: nginx:1.20-alpine
    depends_on:
      - php
    ports:
      - "8080:3000"
    volumes:
      - ./public:/home/unsecure/public:ro
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/local/nginx/access.log:/home/logs/unsecure/access.log
      - ./.docker/local/nginx/error.log:/home/logs/unsecure/error.log
  apache:
      container_name: unsecure-apache
      image: httpd:2.4-alpine
      depends_on:
        - php
      ports:
        - "9090:5000"
      volumes:
        - ./public:/home/unsecure/public:ro
        - ./.docker/local/apache/apache.conf:/usr/local/apache2/conf/httpd.conf:ro
